import { useState, useRef, useEffect } from 'react';
import type { Exercise, MuscleArea, EquipmentType } from '../types';
import {
  getClaudeApiKey,
  loadChatHistory,
  saveChatHistory,
  addCustomExercise,
  loadCustomExercises,
  type ChatMessage,
} from '../data/storage';
import { Button } from './Button';

const SYSTEM_PROMPT = `You are a fitness assistant embedded in a workout tracking PWA. You can help users:

1. Add new exercises to their library
2. Answer fitness/workout questions
3. Suggest workout routines

When the user wants to add an exercise, respond with a JSON block that I can parse. Use this exact format:

\`\`\`exercise
{
  "name": "Exercise Name",
  "area": "squat|hinge|press|push|pull|core|conditioning|warmup|full-body",
  "equipment": "bodyweight|dumbbell|kettlebell|barbell|sandbag|machine|cable|resistance-band",
  "defaultWeight": 50,
  "defaultReps": 10,
  "defaultDuration": null,
  "description": "Brief description of the exercise"
}
\`\`\`

Rules for exercise JSON:
- "area" must be one of: squat, hinge, press, push, pull, core, conditioning, warmup, full-body
- "equipment" must be one of: bodyweight, dumbbell, kettlebell, barbell, sandbag, machine, cable, band
- Use defaultWeight (in lbs) and defaultReps for strength exercises
- Use defaultDuration (in seconds) for timed exercises like planks
- Set unused fields to null

Current custom exercises in the user's library:
{{CUSTOM_EXERCISES}}

Be concise and helpful. When adding exercises, confirm what was added.`;

export function ClaudeChat() {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const apiKey = getClaudeApiKey();

  useEffect(() => {
    setMessages(loadChatHistory());
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const getSystemPrompt = () => {
    const customExercises = loadCustomExercises();
    const exerciseList = customExercises.length > 0
      ? customExercises.map(e => `- ${e.name} (${e.area}, ${e.equipment})`).join('\n')
      : 'None yet';
    return SYSTEM_PROMPT.replace('{{CUSTOM_EXERCISES}}', exerciseList);
  };

  const parseExerciseFromResponse = (content: string): Exercise | null => {
    const exerciseMatch = content.match(/```exercise\n([\s\S]*?)\n```/);
    if (!exerciseMatch) return null;

    try {
      const exerciseData = JSON.parse(exerciseMatch[1]);

      // Validate required fields
      if (!exerciseData.name || !exerciseData.area || !exerciseData.equipment) {
        return null;
      }

      // Validate area
      const validAreas: MuscleArea[] = ['squat', 'hinge', 'press', 'push', 'pull', 'core', 'conditioning', 'warmup', 'full-body'];
      if (!validAreas.includes(exerciseData.area)) {
        return null;
      }

      // Validate equipment
      const validEquipment: EquipmentType[] = ['bodyweight', 'dumbbell', 'kettlebell', 'barbell', 'sandbag', 'machine', 'cable', 'resistance-band'];
      if (!validEquipment.includes(exerciseData.equipment)) {
        return null;
      }

      return {
        id: '', // Will be generated by addCustomExercise
        name: exerciseData.name,
        area: exerciseData.area,
        equipment: exerciseData.equipment,
        defaultWeight: exerciseData.defaultWeight || undefined,
        defaultReps: exerciseData.defaultReps || undefined,
        defaultDuration: exerciseData.defaultDuration || undefined,
        description: exerciseData.description || undefined,
      };
    } catch {
      return null;
    }
  };

  const sendMessage = async () => {
    if (!input.trim() || !apiKey || isLoading) return;

    const userMessage: ChatMessage = {
      role: 'user',
      content: input.trim(),
      timestamp: new Date().toISOString(),
    };

    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    setError(null);
    setIsLoading(true);

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true',
        },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 1024,
          system: getSystemPrompt(),
          messages: newMessages.map(m => ({
            role: m.role,
            content: m.content,
          })),
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `API error: ${response.status}`);
      }

      const data = await response.json();
      const assistantContent = data.content[0]?.text || 'No response';

      // Check if response contains an exercise to add
      const exercise = parseExerciseFromResponse(assistantContent);
      if (exercise) {
        addCustomExercise(exercise);
      }

      const assistantMessage: ChatMessage = {
        role: 'assistant',
        content: assistantContent,
        timestamp: new Date().toISOString(),
      };

      const updatedMessages = [...newMessages, assistantMessage];
      setMessages(updatedMessages);
      saveChatHistory(updatedMessages);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to send message');
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const clearChat = () => {
    setMessages([]);
    saveChatHistory([]);
  };

  if (!apiKey) {
    return (
      <div className="min-h-screen pb-20 flex flex-col bg-slate-100 dark:bg-slate-950">
        <header className="px-4 pt-16 pb-4 safe-top">
          <div className="flex items-center gap-3">
            <img src="/logo_icon.png" alt="Moove" className="h-10 dark:invert" />
            <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">Chat</h1>
          </div>
        </header>
        <div className="flex-1 flex items-center justify-center p-8">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-slate-200 dark:bg-slate-800 flex items-center justify-center">
              <svg className="w-8 h-8 text-slate-400 dark:text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
              </svg>
            </div>
            <h2 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-2">API Key Required</h2>
            <p className="text-slate-500 dark:text-slate-400 mb-6">
              Add your Claude API key in Settings to use the assistant.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen pb-20 flex flex-col bg-slate-100 dark:bg-slate-950">
      {/* Header */}
      <header className="px-4 pt-16 pb-3 safe-top border-b border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src="/logo_icon.png" alt="Moove" className="h-10 dark:invert" />
            <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">Chat</h1>
          </div>
          <button
            onClick={clearChat}
            className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-2"
            title="Clear chat"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
          </button>
        </div>
      </header>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4">
        {messages.length === 0 && (
          <div className="text-center py-12">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-emerald-100 dark:bg-emerald-600/20 flex items-center justify-center">
              <svg className="w-8 h-8 text-emerald-500 dark:text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
              </svg>
            </div>
            <h2 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-2">Ask me anything!</h2>
            <p className="text-slate-500 dark:text-slate-400 text-sm max-w-xs mx-auto">
              I can help you add new exercises, answer fitness questions, or suggest workouts.
            </p>
            <div className="mt-6 space-y-2">
              <button
                onClick={() => setInput('Add a barbell back squat exercise')}
                className="block w-full max-w-xs mx-auto px-4 py-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 text-sm hover:bg-slate-50 dark:hover:bg-slate-700"
              >
                "Add a barbell back squat"
              </button>
              <button
                onClick={() => setInput('What exercises target the posterior chain?')}
                className="block w-full max-w-xs mx-auto px-4 py-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 text-sm hover:bg-slate-50 dark:hover:bg-slate-700"
              >
                "What exercises target the posterior chain?"
              </button>
            </div>
          </div>
        )}

        {messages.map((msg, i) => (
          <div
            key={i}
            className={`mb-4 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}
          >
            <div
              className={`inline-block max-w-[85%] px-4 py-3 rounded-2xl ${
                msg.role === 'user'
                  ? 'bg-emerald-600 text-white rounded-br-md'
                  : 'bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100 border border-slate-200 dark:border-slate-700 rounded-bl-md'
              }`}
            >
              <div className="whitespace-pre-wrap text-sm">{formatMessage(msg.content)}</div>
            </div>
          </div>
        ))}

        {isLoading && (
          <div className="mb-4 text-left">
            <div className="inline-block px-4 py-3 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-bl-md">
              <div className="flex gap-1">
                <div className="w-2 h-2 bg-slate-400 dark:bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                <div className="w-2 h-2 bg-slate-400 dark:bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                <div className="w-2 h-2 bg-slate-400 dark:bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
              </div>
            </div>
          </div>
        )}

        {error && (
          <div className="mb-4 px-4 py-3 rounded-xl bg-red-100 dark:bg-red-500/20 border border-red-300 dark:border-red-500/30 text-red-600 dark:text-red-400 text-sm">
            {error}
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="px-4 py-4 bg-white/95 dark:bg-slate-900/95 border-t border-slate-200 dark:border-slate-800">
        <div className="flex gap-3">
          <textarea
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask about exercises, workouts..."
            rows={1}
            className="flex-1 px-4 py-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-slate-100 placeholder-slate-400 dark:placeholder-slate-500 focus:outline-none focus:border-emerald-500 resize-none"
          />
          <Button
            variant="primary"
            onClick={sendMessage}
            disabled={!input.trim() || isLoading}
            className="px-4"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </Button>
        </div>
      </div>
    </div>
  );
}

// Format message to hide JSON blocks and show friendly version
function formatMessage(content: string): string {
  // Replace exercise JSON blocks with a friendly message
  return content.replace(
    /```exercise\n[\s\S]*?\n```/g,
    '[Exercise added to your library]'
  );
}
